// Beginning of global variables
/** The host URL */
var api = "http://api.giphy.com/v1/gifs/random?";
/** The public beta key */
var apiKey = "&api_key=dc6zaTOxFJmzC";
/** The query; the + character for phrases consisting of 2+ words */
var query = "&tag=funny+cat";
/** True if the user wants to load from Giphy's entire collection; false
 * if they want to limit their search to the query */
var searchAll = true;
// End of global variables

/**
 * Contains code that is executed once when the program begins.
 */
function setup() {
  noCanvas();
  var url = getGiphyURL();
  loadJSON(url, gotData);
}

/**
 * Creates the URL for the Giphy request.
 * @return A string
 */
function getGiphyURL() {
  var url = api + apiKey;
  if (!searchAll) url += query;
  return url;
}

/**
 * Callback function for the p5.js function loadJSON, which takes a URL and returns
 * results in JSON format. Extracts the URL for the gif corresponding to the index
 * (global var) and uses p5's createImg function to embed it in an <img src=...> tag
 * to display it onscreen.
 * @param giphyData - A JSON object generated by Giphy
 */
function gotData(giphyData) {
  gif = giphyData.data.image_url;
  createImg(gif);
}