/** The host URL */
var api = "http://api.giphy.com/v1/gifs/trending?";

/** The public beta key */
var apiKey = "&api_key=dc6zaTOxFJmzC";

/** The query; the + character for phrases consisting of 2+ words */
var query = "&tag=funny+cat";

/** True if the user wants to load from Giphy's entire collection; false
 * if they want to limit their search to the query */
var searchAll = true;

/** The number of gifs loaded by default when querying trending gifs. */
var numTrendingGifs = 25;

/**
 * Contains code that is executed once when the program begins.
 */
function setup() {
  noCanvas();
  var url = getGiphyURL();
  loadJSON(url, gotData);
}

/**
 * Creates the URL for the Giphy request.
 * @return A string
 */
function getGiphyURL() {
  var url = api + apiKey;
  if (!searchAll) url += query;
  return url;
}

/**
 * Callback function for the p5.js function loadJSON, which takes a URL and returns
 * results in JSON format. Extracts the URL for the gif corresponding to the index
 * (global var) and uses p5's createImg function to embed it in an <img src=...> tag
 * to display it onscreen.
 * @param giphyData - A JSON object generated by Giphy
 */
function gotData(giphyData) {
  var randIndex = floor(random(numTrendingGifs - 1));
  gif = giphyData.data[randIndex].images.fixed_height.url;
  //createImg(gif);
  console.log(gif);
}
